version: '3.8'

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16  # Define a custom subnet for the backend network
  
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16  # Define a custom subnet for the frontend network

services:
  db-admin:
    container_name: comet-db-admin
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    ports:
      - 8081:80

  db:
    container_name: comet-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: x7#r%^s2!wxXsw$%s223@rq
    networks:
      - backend
    volumes:
      - ./sql/data:/var/lib/mysql
    ports:
      - "3306:3306" 
    command: --max_allowed_packet=64M

  account:
    container_name: comet-account
    image: comet/account
    build: 
      context: .
      args:
        - debug
    networks:
      backend:
        ipv4_address: 172.20.0.22  # Assign a specific IP address in the backend network
      frontend:
        ipv4_address: 172.21.0.22  # Assign a specific IP address in the frontend network
    ports:
      - 9958:9958
    depends_on:
      - db
    entrypoint: ["/wait-for-it.sh", "comet-db:3306", "--"]
    command: ["dotnet", "./Comet.Account/Comet.Account.dll", "/Database:Hostname=comet-db"]

  game:
    image: comet/server
    build: 
      context: .
      args:
        - debug
    networks:
      backend:
        ipv4_address: 172.20.0.4  # Assign a specific IP address in the backend network
      frontend:
        ipv4_address: 172.21.0.4  # Assign a specific IP address in the frontend network
    ports:
      - 5816:5816
    depends_on:
      - db
    entrypoint: ["/wait-for-it.sh", "comet-db:3306", "--"]
    command: ["dotnet", "./Comet.Game/Comet.Game.dll", "/Database:Hostname=comet-db"]
